"""
export_utils.py
------------------
Utility functions for exporting agent output as a clean, downloadable
bug ticket — combining Bug Analysis + Evidence Agent output (and optionally
Orchestrator output) into one Markdown document a tester can paste
directly into Jira, GitHub Issues, Azure DevOps, etc.

WHY THIS MATTERS:
Judges and real QA teams care about the *output artifact*, not just the
chat-style answer. A one-click "Download Ticket" turns QA Copilot from a
Q&A tool into something that produces a real, usable business deliverable.
"""

from datetime import datetime


def build_bug_ticket_markdown(
    bug_description: str,
    triage_section: str = "",
    evidence_section: str = "",
    regression_tests_section: str = "",
) -> str:
    """
    Combines whatever sections are available into one clean Markdown
    bug-ticket document, ready to paste into any issue tracker.

    Any section left empty is simply omitted from the final document,
    so this works whether it's called from a single agent tab or from
    the full Orchestrator flow.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    parts = [
        f"# 🐞 Bug Ticket — Generated by QA Copilot",
        f"*Generated on {timestamp}*",
        "",
        "## Issue Description",
        bug_description.strip(),
        "",
    ]

    if triage_section.strip():
        parts.append("## Triage")
        parts.append(triage_section.strip())
        parts.append("")

    if regression_tests_section.strip():
        parts.append("## Suggested Regression Test Cases")
        parts.append(regression_tests_section.strip())
        parts.append("")

    if evidence_section.strip():
        parts.append("## Evidence Checklist")
        parts.append(evidence_section.strip())
        parts.append("")

    parts.append("---")
    parts.append("*Generated using QA Copilot — AI Agent Suite for Testers.*")

    return "\n".join(parts)


def build_filename(prefix: str = "qa_copilot_ticket") -> str:
    """Generates a timestamped filename for the downloaded ticket."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{prefix}_{timestamp}.md"
